- name: Install htop and Apache Web Server
  hosts: all
  connection: local
  become: true

  tasks:
    - name: Update apt cache 
      apt:
        update_cache: yes

    - name: Install htop
      apt:
        name: htop
        state: present

    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    - name: Ensure Apache service is running and enabled at boot
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Verify that Apache is responding on port 80
      uri:
        url: http://localhost
        return_content: yes
      register: apache_response

    - name: Show Apache test page output
      debug:
        msg: "Apache is up and responding with status: {{ apache_response.status }}"
